# Generated by Django 2.1.3 on 2019-04-30 21:31

import django.core.validators
from django.db import migrations, models
import home.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to=home.utils.get_doc_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['excel'])])),
            ],
        ),
    ]
