# Generated by Django 2.1.3 on 2019-04-30 21:38

import django.core.validators
from django.db import migrations, models
import home.utils


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='excel_file',
            field=models.FileField(upload_to=home.utils.get_doc_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlxs'])]),
        ),
    ]
