# Generated by Django 2.1.3 on 2019-05-01 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190501_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdata',
            name='xl_file',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.ExcelFile'),
            preserve_default=False,
        ),
    ]
