# Generated by Django 2.1.3 on 2019-05-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_graphdata_xl_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graphdata',
            unique_together={('xl_file', 'coordinates')},
        ),
    ]
